const userPermissions = {
	CHANGE_ACCOUNT_DATA: "changeAccountData",
	CHANGE_ACCOUNT_OWNER: "changeAccountOwner",
	CHANGE_APP_STATUS: "changeAppStatus",
	CHANGE_PLAN: "changePlan",
	COMPLETE_PERSONA_MODAL: "completePersonaModal",
	DELETE_ACCOUNT: "deleteAccount",
	DELETE_USER: "deleteUser",
	OPEN_HOSTED_PAGE: "openHostedPage",
	SHOW_PLAN_UPGRADE: "showPlanUpgradeModal",
	INVITE_USER: "inviteUser",
	VIEW_DASHBOARD_LAST_USED: "viewDashboardLastUsed",
	VIEW_DASHBOARD_TAX_ESTIMATOR: "viewDashboardTaxEstimator",
	VIEW_PLAN_DETAILS: "viewPlanDetails",
	//CHANGE_ACCOUNT_DATA: 'changeAccountData',
	RECEIVE_NOTIFCATIONS: "receiveNotification",
	UPDATE_EMAIL_INTEGRATION: "updateEmailIntegrationAccount",
	MODIFY_EMAIL_NOTIFICATIONS: "notificationEmailMobile",
	MODIFY_SEE_GST_REPORTS: "viewTaxConsultantExport",
	CUSTOMER_IMPORT: "customerImport",
	ARTICLE_IMPORT: "articleImport",
	VIEW_TERMS_PAYMENT: "viewTermsOfPayment",
	UPDATE_TERMS_PAYMENT: "updateTermsOfPayment",
	DELETE_TERMS_PAYMENT: "deleteTermsOfPayment",
	SET_DEFAULT_TERM: "setDefaultPaymentTerm",
	VIEW_TEXT_MODULES: "viewTextBlocks",
	UPDATE_TEXT_MODULES: "updateTextBlocks",
	VIEW_DUNNING: "viewDunningProcess",
	UPDATE_DUNNING: "updateDunningProcess",
	VIEW_NUMBER_RANGE: "viewNumberRange",
	UPDATE_NUMBER_RANGE: "updateNumberRange",
	UPDATE_SALUTATIONS: "updateSalutationsTitleCategories",
	DOWNLOAD_INVOICE: "downloadInvoice",
	SEND_INVOICE: "sendInvoice",
	PRINT_INVOICE: "printInvoice",
	COPY_LINK_INVOICE: "copyLinkInvoice",
	CREATE_INVOICE: "createInvoice",
	UPDATE_INVOICE: "updateInvoice",
	CLOSE_INVOICE: "closeInvoice",
	CANCEL_INVOICE: "cancelInvoice",
	CREATE_INVOICE_REMINDER: "createInvoiceReminder",
	ENTER_INVOICE_PAYMENT: "enterInvoicePayment",
	DELETE_INVOICE: "deleteInvoice",
	VIEW_INVOICE: "viewInvoice",
	// DELIVERY CHALLAN
	CREATE_CHALLAN: "createDeliveryChallan",
	UPDATE_CHALLAN: "updateChallan",
	CLOSE_CHALLAN: "closeChallan",
	CANCEL_CHALLAN: "cancelChallan",
	DELETE_CHALLAN: "deleteChallan",
	ENTER_CHALLAN_PAYMENT: "enterChallanPayment",
	VIEW_CHALLAN: "viewChallan",
	ACCEPT_CHALLAN: "acceptChallan",
	DECLINE_CHALLAN: "declineChallan",
	SET_OPEN_CHALLAN: "setOpenChallan",

	// RECURRING INVOICES
	VIEW_RECURRING_INVOICE: "viewRecurringInvoice",
	CREATE_RECURRING_INVOICE: "createRecurringInvoice",
	UPDATE_RECURRING_INVOICE: "updateRecurringInvoice",
	DELETE_RECURRING_INVOICE: "deleteRecurringInvoice",
	START_RECURRING_INVOICE: "startRecurringInvoice",
	FINISH_RECURRING_INVOICE: "finishRecurringInvoice",
	// TIMESHEET
	VIEW_TIMESHEET: "viewTimeTracking",
	CREATE_TIMESHEET: "createTimeTracking",
	UPDATE_TIMESHEET: "updateTimeTracking",
	DELETE_TIMESHEET: "deleteTimeTracking",
	// Quotations
	VIEW_OFFER: "viewOffer",
	CREATE_OFFER: "createOffer",
	UPDATE_OFFER: "updateOffer",
	DELETE_OFFER: "deleteOffer",
	ACCEPT_OFFER: "acceptOffer",
	REJECT_OFFER: "rejectOffer",
	SET_OPEN_OFFER: "setOpenOffer",
	// Imprezz Quotations
	VIEW_IMPREZZ_OFFER: "viewImpressOffer",
	CREATE_IMPREZZ_OFFER: "createImpressOffer",
	UPDATE_IMPREZZ_OFFER: "updateImpressOffer",
	DELETE_IMPREZZ_OFFER: "deleteImpressOffer",
	ACCEPT_IMPREZZ_OFFER: "acceptImpressOffer",
	REJECT_IMPREZZ_OFFER: "rejectImpressOffer",
	FINALIZE_IMPREZZ_OFFER: "finalizeImpressOffer",
	// Customers
	VIEW_CUSTOMER: "viewCustomer",
	CREATE_CUSTOMER: "createCustomer",
	UPDATE_CUSTOMER: "updateCustomer",
	DELETE_CUSTOMER: "deleteCustomer",
	// Articles
	VIEW_ARTICLE: "viewArticle",
	CREATE_ARTICLE: "createArticle",
	UPDATE_ARTICLE: "updateArticle",
	DELETE_ARTICLE: "deleteArticle",
	VIEW_ARTICLE_SALES_OVERVIEW: "viewArticleSalesOverview",
	//Expenses
	CREATE_EXPENSE: "createExpense",
	VIEW_EXPENSE: "viewExpense",
	UPDATE_EXPENSE: "updateExpense",
	DELETE_EXPENSE: "deleteExpense",
	// Purchase Orders
	CREATE_PURCHASE_ORDER: "createPurchaseOrder",
	VIEW_PURCHASE_ORDER: "viewPurchaseOrder",
	DELETE_PURCHASE_ORDER: "deletePurchaseOrder",
	UPDATE_PURCHASE_ORDER: "updatePurchaseOrder",
	CONVERT_PURCHASE_ORDER: "convertPurchaseOrderToExpense",
	SET_PURCHASE_ORDER_OPEN: "setPurchaseOrderOpen",
	REJECT_PURCHASE_ORDER: "rejectPurchaseOrder",
	ACCEPT_PURCHASE_ORDER: "acceptPurchaseOrder",
	// DASHBOARD
	VIEW_DASHBOARD: "viewDashboardSalesAndExpenseStatistics",
	EDIT_NUMERIC_RANGES: "updateNumberRange",
	// Stock Movement
	VIEW_STOCK_MOVEMENT: "viewStockMovement",
	CREATE_STOCK_MOVEMENT: "createStockMovement",
	DELETE_STOCK_MOVEMENT: "deleteStockMovement",
	// GST Reports
	CREATE_GST_EXPORTS: "createGstExports",
};

export default Object.freeze(userPermissions);
