const WebStorageKey = {
  REGISTRATION_EMAIL: "REGISTRATION_EMAIL",
  LOGIN_TOKEN_KEY: "LOGIN_TOKEN_KEY",
  LOGIN_TOKEN_START_TIME: "LOGIN_TOKEN_START_TIME",
};

export default Object.freeze(WebStorageKey);
